apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kaniko-builder
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
      imagePullPolicy: IfNotPresent

    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      imagePullPolicy: Always
      args: ["run", "--dockerfile=/dev/null"]
      volumeMounts:
        - name: jenkins-docker-cfg
          mountPath: /home/jenkins/.docker
          readOnly: true
      env:
        - name: DOCKER_CONFIG
          value: /home/jenkins/.docker

  volumes:
    - name: jenkins-docker-cfg
      secret:
        secretName: my-registry-secret
