apiVersion: v1
kind: Pod
metadata:
  labels:
    app: kaniko-builder
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: Always
      tty: true
      volumeMounts:
        - name: registry-secret
          mountPath: /kaniko/.docker
          readOnly: true
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker

    - name: jnlp
      image: jenkins/inbound-agent:latest
      imagePullPolicy: IfNotPresent

  volumes:
    - name: registry-secret
      secret:
        secretName: my-registry-secret
