apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: builder-pvc
  namespace: jenkis
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 6Gi
