image:
  repository: docker-registry.docker-registry.svc.cluster.local:5000/front
  tag: "01"
  pullPolicy: Always

imagePullSecrets: "my-registry-secret"

service:
  port: 443

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
  path: "/"
  host: "api.domain.com"
  pathType: Prefix
