FROM eclipse-temurin:21-jdk-jammy

RUN apt-get update && \
    apt-get install -y wget unzip && \
    wget https://services.gradle.org/distributions/gradle-8.12-bin.zip -O /tmp/gradle.zip && \
    unzip -d /opt /tmp/gradle.zip && \
    rm /tmp/gradle.zip && \
    apt-get remove -y wget unzip && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV PATH="/opt/gradle-8.12/bin:$PATH"

COPY ./back-end /app

WORKDIR /app

RUN gradle build --no-daemon

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "/app/build/libs/ci-back-end-0.0.1-SNAPSHOT.jar"]
