apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-bind
  namespace: app
subjects:
  - kind: ServiceAccount
    name: default
    namespace: jenkis
roleRef:
  kind: Role
  name: role-bind
  apiGroup: rbac.authorization.k8s.io
