apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: app
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-retain
  resources:
    requests:
      storage: 1Gi
